### ISSUE TITLE
Installation error - issue with Python environment?

### ISSUE THREAD

**Issue by drjgauthier** [ML4LHS/clinspacy#2]
Howdy!
I tried installing your package but I'm having the following error message:

* installing *source* package ‘clinspacy’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘clinspacy’:
 .onLoad failed in loadNamespace() for 'clinspacy', details:
  call: NULL
  error: could not find a Python environment for /usr/bin/python
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/clinspacy’
Error: Failed to install 'clinspacy' from GitHub:
  (converted from warning) installation of package ‘/var/folders/_p/rj_4wpfn3mv509zz_jvf37180000gp/T//RtmpHBafD8/file3a1d274e385c/clinspacy_0.1.0.9001.tar.gz’ had non-zero exit status

Thoughts?

**Comment by poldham** [comment]
Just confirming this issue.

**Comment by kdpsingh** [comment]
Thanks @poldham. In talking with @drjgauthier in this Twitter thread (https://twitter.com/drjgauthier/status/1296131812016533504?s=21) it sounds like the initial issue is resolved (that Python couldn't be located). The new error is that installation freezes at: "** testing if installed package can be loaded from temporary location"

I'm planning to open a separate issue for that. Although related to installation, the underlying issue is potentially different.

@poldham, can you try this to see if this resolves your issue:

`reticulate::install_miniconda()`

and then try reinstalling clinspacy.

**Comment by poldham** [comment]
Thanks @kdpsingh, yes that sounds right. I will dig around and see how it goes. As a regular spacy user it is great to see this pkg coming out! Best and thanks, Paul

**Comment by kdpsingh** [comment]
Thanks @poldham -- I will plan to update the README with instructions on installing miniconda (or in trying to have the package install it for you after confirming with the user).

If you're able to, let me know if that resolves the issue so that I can make that change and close this issue. Thanks!

**Comment by poldham** [comment]
Ok thanks @kdpsingh. The [spacyr](https://cran.r-project.org/web/packages/spacyr/vignettes/using_spacyr.html) documentation is pretty good on installing miniconda and spacy and may be helpful for writing the documentation. As I will be shortly be away please go ahead and close as that will solve the issue I think.

**Comment by kdpsingh** [comment]
> Ok thanks @kdpsingh. The [spacyr](https://cran.r-project.org/web/packages/spacyr/vignettes/using_spacyr.html) documentation is pretty good on installing miniconda and spacy and may be helpful for writing the documentation. As I will be shortly be away please go ahead and close as that will solve the issue I think. 

Thanks. Yes, I've been trying to take advantage of new `reticulate` features that enable the user to install an R package with Python dependencies without the need for a separate install_spacy() function.

My impression from reading `reticulate` documentation was that the `reticulate::configure_environment()` function, if placed in the packaging loading script, would automatically prompt the user to install miniconda if Python couldn't be found. It looks like that is not the case (or I'm using it incorrectly).

I've read the `spacyr` docs on how they set up spacy (which was borrowed from the `tensorflow` R package) but intentionally tried to go a different route due to new `reticulate` features. Prompting the user to install `miniconda` automatically shouldn't be too difficult so I'll plan to address this in an update.

**Comment by kdpsingh** [comment]
My planned fix:
- Check if miniconda is installed. If not, install it.
- Create a "clinspacy" conda virtual environment for the package
- Use the "clinspacy" virtual environment for the package-specific dependencies

This will hopefully minimize dependency and version-related conflicts with other Python environments.

**Comment by kdpsingh** [comment]
@drjgauthier When you get a chance see if the latest commit takes care of the installation issue for you. If not, let me know what OS you are using and which R. So far, I've only tested it on Windows and in R 3.6.

**Comment by drjgauthier** [comment]
I've just installed and loaded {clinspacy} successfully!

**Comment by kdpsingh** [comment]
> I've just installed and loaded {clinspacy} successfully!

Great! Let me know if you run into issues the first time you run clinspacy(). Will close this issue for now.
